### ISSUE TITLE
Make it possible to use component without depending on Vuetify

### ISSUE THREAD

**Issue by karoletrych** [karoletrych/vue-cron-editor#2]
Its logic could be used with other frameworks than Vuetify this way

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leonardder** [comment]
I'd really like embedding this component without having the dependency on vuetify

**Comment by karoletrych** [comment]
Unfortunately, Vuetify requires putting some components (e.g. VTabs used in vue-cron-editor) inside v-app element. I'd like to avoid putting v-app inside the vue-cron-editor because the v-apps cannot be nested.

I tried porting the VueCronEditor.vue file to Buefy and it looks promising. 

I think I'm gonna create 2 target packages vue-cron-editor-vuetify and vue-cron-editor-buefy reusing the common logic in vueCronEditorMixin.ts and cronExpressions.ts.

**Comment by karoletrych** [comment]
The vue-cron-editor-buefy is the recommended package since now. It doesn't require the dependency to vuetify.
