### ISSUE TITLE
Limit tabs to Daily, Weekly, Monthly

### ISSUE THREAD

**Issue by danpartus** [karoletrych/vue-cron-editor#51]
I was wondering if there is a way to limit the tabs that show on the editor. I just need to show Daily, Weekly, Monthly.

Thanks!

**Comment by danpartus** [comment]
Just checking in. Not sure if the thumbs up meant this can be done, or this is something you are going to incorporate into the package? Thanks!

**Comment by karoletrych** [comment]
I’m going to incorporate this into the package. I think it could be easily done a doesn’t conflict too much with other work (quartz format support) so i’ll try to add this feature today. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karoletrych** [comment]
Added in 0.2.13.
