### ISSUE TITLE
When clicking "advanced" I get TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by VictorioBerra** [karoletrych/vue-cron-editor#56]
at parseExpression (vue-cron-editor-vuetify.umd.js?3587:214)

Any way to fix?

**Comment by ocraciun** [comment]
I get the same error when parsing a previous saved expression for minutes/day tab. Did you find a fix for this @VictorioBerra?

**Comment by karoletrych** [comment]
@ocraciun 
Was the expression inputted by vue-cron-editor? IIRC only one format is allowed */1 * * * * is allowed but * * * * * is not.
This issue references this:
https://github.com/karoletrych/vue-cron-editor/issues/28

**Comment by ocraciun** [comment]
Hi @karoletrych 
Yes, the expression was inputted by vue-cron-editor in quartz format. For example, on hourly tab this is the expression generated by the component in v-model: 0 0 0/1 * * ?, but when I initialize the component with this value it shows the error

**Comment by karoletrych** [comment]
The expression seems to parse fine. I've fixed the edit buttons in the CRUD sample at: karoletrych.github.io/vue-cron-editor/ so you can check if it works there (seems to work for me).
The code for the sample is here: 
https://github.com/karoletrych/vue-cron-editor/blob/master/src/App.vue

**Comment by karoletrych** [comment]
I've changed the sample1CronExpression to "0 0 0/1 * * ?" and selectedSyntax: "quartz" so that the component starts with this expression and it seems to load fine.

**Comment by ocraciun** [comment]
All good. Fixed the issue by clearing the npm cache and installing the package again. Thanks a lot!
